stuff/dapps/my_app/hello/models.py
MESSAGES = {
    'default': 'Hello to the World of Flask!',
}

stuff/dapps/my_app/product/models.py
PRODUCTS = {
    'iphone': {
        'name': 'iPhone 5S',
        'category': 'Phones',
        'price': 699,
    },
    'galaxy': {
        'name': 'Samsung Galaxy 5',
        'category': 'Phones',
        'price': 649,
    },
    'ipad-air': {
        'name': 'iPad Air',
        'category': 'Tablets',
        'price': 649,
    },
    'ipad-mini': {
        'name': 'iPad Mini',
        'category': 'Tablets',
        'price': 549
    }
}

stuff/dapps/my_app/__init__.py
from flask import Flask
from my_app.product.views import product_blueprint
app = Flask(__name__)
app.register_blueprint(product_blueprint)

stuff/dapps/my_app/hello/__init__.py
#no code just to make hello/ python module

stuff/dapps/my_app/hello/views.py
from flask import Blueprint
from my_app.hello.models import MESSAGES
hello = Blueprint('hello', __name__)
@hello.route('/')
@hello.route('/hello')
def hello_world():
    return MESSAGES['default']
@hello.route('/show/<key>')
def get_message(key):
    return MESSAGES.get(key) or "%s not found!" % key
@hello.route('/add/<key>/<message>')
def add_or_update_message(key, message):
    MESSAGES[key] = message
    return "%s Added/Updated" % key

stuff/dapps/my_app/product/__init__.py
# from flask import Flask
# from my_app.product.views import product_blueprint
# app = Flask(__name__)
# app.register_blueprint(product_blueprint)

stuff/dapps/my_app/product/views.py
from werkzeug.exceptions import abort
from flask import render_template
from flask import Blueprint
from my_app.product.models import PRODUCTS
product_blueprint = Blueprint('product', __name__)
@product_blueprint.route('/')
@product_blueprint.route('/home')
def home():
    return render_template('home.html', products=PRODUCTS)
@product_blueprint.route('/product/<key>')
def product(key):
    product = PRODUCTS.get(key)
    if not product:
        abort(404)
    return render_template('product.html', product=product)
@product_blueprint.context_processor
def some_processor():
    def full_name(product):
        return '{0} / {1}'.format(product['category'],
          product['name'])
    return {'full_name': full_name}

stuff/dapps/my_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,
      initial-scale=1">
    <title>product stuff from book</title>
    <link href="{{ url_for('static',
      filename='css/bootstrap.min.css') }}"
      rel="stylesheet">
    <link href="{{ url_for('static',
      filename='css/main.css') }}" rel="stylesheet">
    <script src="{{ url_for('static',
      filename='js/moment.min.js') }}"></script>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark fixed-top"
      role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="{{
            url_for('product.home') }}">Flask Cookbook</a>
        </div>
      </nav>
    </div>
    <div class="container">
    {% block container %}{% endblock %}
    </div>
    <script src="{{ url_for('static',
      filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static',
      filename='js/bootstrap.bundle.min.js') }}"></script>
  </body>
</html>

stuff/dapps/my_app/templates/home.html
{% extends 'base.html' %}
{% block container %}
  <div class="top-pad">
    {% for id, product in products.items() %}
    <div class="top-pad offset-1 col-sm-10">
      <div class="card text-center">
        <div class="card-body">
          <h2>
            <a href="{{ url_for('product.product', key=id)
              }}">{{ product['name'] }}</a>
            <small>$ {{ product['price'] }}</small>
          </h2>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
{% endblock %}

stuff/dapps/my_app/templates/index.html
<head>
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">

<body>
    <div class="App">
        <header class="App-header">
            <img src="{{ url_for('static', filename='Octocat.png') }}" class="App-logo" alt="logo" />
            <p>
                GitHub Codespaces <span class="heart">♥️</span> Flask
            </p>
            <p class="small">
                Edit <code>templates/index.html</code> and refresh to see your changes!
            </p>
        </header>
    </div>
</body>

</html>

stuff/dapps/my_app/templates/product.html
{% extends 'home.html' %}
{% block container %}
  <div class="top-pad">
    <h4>{{ full_name(product) }}</h4>
    <h1>{{ product['name'] }}</h1>
    <h3><small>{{ product['category'] }}</small></h3>
    <h5>$ {{ product['price'] }}</h5>
  </div>
{% endblock %}